#!/bin/sh
#
# @name PRISM Quadcopter
#
# @type Quadrotor x
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 feed-through of RC AUX1 channel
# @output MAIN6 feed-through of RC AUX2 channel
#
# @output AUX1 feed-through of RC AUX1 channel
# @output AUX2 feed-through of RC AUX2 channel
# @output AUX3 feed-through of RC AUX3 channel
# @output AUX4 feed-through of RC FLAPS channel
#
# @maintainer Jacob Dahl <jake@wattsinnovations.com>
#

. ${R}etc/init.d/rc.mc_defaults

set MIXER quad_x

set PWM_OUT 1234

param set-default PROPULSION_GROUP 1

# TODO: once we do bringup, this is where all default parameters will go

# Example
#
# param set-default BAT_CAPACITY 4500
# param set-default BAT_LOW_THR 0.20
# param set-default BAT_CRIT_THR 0.15
# param set-default BAT_EMERGEN_THR 0.10
#
